name: trufflehog-secret-scan-workflow
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  push:
    branches:
      - "**"

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
  
jobs:

  trufflehog-sast-scan-without-repourl:
    steps:
      - name: checkout Source Code
        uses: cloudbees-io/checkout@v1

      - name: Run TruffleHog SAST Action
        uses: cloudbees-io/trufflehog-secret-scan-code@v1
        with:
          branch: "${{ cloudbees.scm.branch }}"

  trufflehog-sast-scan-with-threshold:
    steps:
      - name: checkout Source Code
        uses: cloudbees-io/checkout@v1

      - name: Run TruffleHog SAST Action
        uses: cloudbees-io/trufflehog-secret-scan-code@v1
        with:
          branch: "${{ cloudbees.scm.branch }}"
          threshold-very-high: 5
